In [1]:
import pandas

In [2]:
ds = pandas.read_csv("Salary_Data.csv")

In [3]:
ds.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [6]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [8]:
x=ds["YearsExperience"]
x=x.values

In [9]:
x=x.reshape(30,1)

In [19]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [10]:
y = ds["Salary"]

In [28]:
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = LinearRegression()

In [13]:
model.fit(x,y)

LinearRegression()

In [14]:
model.coef_

array([9449.96232146])

In [15]:
model.predict([[2.5]])

array([49417.10600231])

In [16]:
# y = wx
model.predict([[10.5]])

array([125016.80457395])

In [17]:
model.predict([[1.1]])

array([36187.15875227])

In [18]:
# Accuracy
36187/39343 * 100
# 91 % :- good accuracy

91.97824263528454

In [19]:
model.predict([[0]])

array([25792.20019867])

In [20]:
# y = wx + c
# c : intercept/slope
model.intercept_

25792.20019866871

In [21]:
# 25792.20019866871 + 9449.96232146*1.1 = 36187.158752274714
# c + wx = y
model.predict([[1.1]])

array([36187.15875227])

In [22]:
import joblib

In [23]:
joblib.dump(model, 'salaryprediction.pk1')

['salaryprediction.pk1']